// @ts-check

/**
 * OpenWoo documentation site — openwoo.app.
 *
 * OpenWoo is part of the Conduction family but carries its own identity:
 * the site runs on plain @docusaurus/preset-classic with the OpenWoo
 * design tokens (NL Design System) from @conduction/theme. The generated
 * design-tokens.css scopes all variables under .openwoo-theme — applied
 * site-wide by src/theme/Root.js — and src/css/custom.css bridges those
 * tokens onto Docusaurus/Infima variables.
 *
 * The openwoo theme has no dark variant, so dark mode is disabled.
 *
 * Audience: implementing teams (gemeente IT, leverancier, partner).
 * Commercial copy lives on www.conduction.nl/solutions/openwoo;
 * tutorials + community-meeting videos live on
 * www.conduction.nl/academy/?app=openwoo.
 */

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'OpenWoo',
  tagline: 'Een publicatieplatform voor alle overheidsbronnen, op je Nextcloud.',
  url: 'https://openwoo.app',
  baseUrl: '/',
  favicon: 'img/favicon.svg',

  organizationName: 'ConductionNL',
  projectName: 'openwoo-app-website',

  onBrokenLinks: 'warn',
  trailingSlash: true,

  /* Nederlands first; the Dutch government is the primary audience.
     English follows once the docs/ markdown is mirrored under i18n/en/. */
  i18n: {
    defaultLocale: 'nl',
    locales: ['nl'],
    localeConfigs: {
      nl: {label: 'Nederlands', htmlLang: 'nl-NL', direction: 'ltr'},
    },
  },

  /* Mermaid diagram rendering for ```mermaid code blocks (used by
     docs/Architecture/federatief-zoeken.md). Theme loaded below. */
  markdown: {
    mermaid: true,
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: 'https://github.com/ConductionNL/openwoo-app-website/tree/main/',
        },
        blog: false,
        theme: {
          /* OpenWoo design tokens (NL Design System) from @conduction/theme,
             scoped under the .openwoo-theme class applied in src/theme/Root.js.
             font.css: the OpenWoo brand font is Arial (a system font), so no
             webfont preconnect/head tags are needed.
             nlds-bridge.css translates the theme's tokens onto the site's
             --site-* vocabulary and Infima's --ifm-* variables — it is the
             ONLY file to touch (besides this list and Root.js) when swapping
             to another NLDS theme. custom.css holds the component rules and
             consumes only site, utrecht and ifm variables. */
          customCss: [
            require.resolve('@conduction/theme/other/openwoo-design-tokens/dist/design-tokens.css'),
            require.resolve('@conduction/theme/other/openwoo-design-tokens/dist/font.css'),
            require.resolve('./src/css/nlds-bridge.css'),
            require.resolve('./src/css/custom.css'),
          ],
        },
      },
    ],
    /* Redocusaurus renders two OAS specs side by side:
       - /api/                — the SECONDARY OpenRegister-direct API.
         Auto-mirrored from an upstream OpenRegister deployment (see
         docs/api.md). The sync step prepends a "this is the secondary
         layer" banner to info.description; the banner is idempotent so
         re-runs against unchanged upstream produce no diff.
       - /api/publications/   — the PRIMARY OpenCatalogi Publications
         API. Hand-curated in static/oas/opencatalogi-publications.json
         because OpenCatalogi doesn't expose its own OAS endpoint yet
         (verified 2026-06-25). Edit that JSON directly when the
         upstream API contract changes. See docs/api.md for the
         architecture context + upstream-link hub. */
    [
      'redocusaurus',
      {
        specs: [
          {
            id: 'woo',
            spec: 'static/oas/woo.json',
            route: '/api/',
          },
          {
            id: 'opencatalogi-publications',
            spec: 'static/oas/opencatalogi-publications.json',
            route: '/api/publications/',
          },
        ],
        theme: {
          /* OpenWoo brand green (--openwoo-color-green-46). */
          primaryColor: '#23845c',
        },
      },
    ],
  ],

  themes: ['@docusaurus/theme-mermaid'],

  themeConfig: {
    colorMode: {
      defaultMode: 'light',
      /* The openwoo token set has no dark variant; a dark toggle would
         render half-styled pages. Switch stays off until the tokens
         grow a dark mode. */
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },

    /* Navbar ported from the old openwoo.app (Open Webconcept) menu so
       long-time users land in familiar places. Product + Techniek link
       to the category-index pages auto-generated by sidebars.js.
       Solution + Academy bridge to the conduction.nl surfaces that own
       the commercial copy and the community videos. */
    navbar: {
      title: '',
      logo: {
        alt: 'OpenWoo logo',
        src: 'img/openwoo-logo.svg',
        height: 64,
      },
      items: [
        {to: '/docs/category/reference/',                            label: 'Product',  position: 'left'},
        {to: '/docs/category/architectuur/',                         label: 'Techniek', position: 'left'},
        {to: '/docs/api-overview',                                   label: 'API',      position: 'left'},
        {href: 'https://www.conduction.nl/solutions/openwoo',        label: 'Solution', position: 'left'},
        {href: 'https://www.conduction.nl/academy/?app=openwoo',     label: 'Academy',  position: 'left'},
        {href: 'https://openwebconcept.nl/',                         label: 'Over Open Webconcept', position: 'right'},
        {href: 'https://samenorganiseren.slack.com/archives/C067Q3UE9F0', label: 'Slack',  position: 'right'},
        {href: 'https://github.com/ConductionNL/openwoo-app-website',    label: 'GitHub', position: 'right'},
      ],
    },

    /* Standard Docusaurus footer in OpenWoo identity: light style with
       the OpenWoo logo. The Conduction column stays as a family link,
       without the Conduction brand decoration. */
    footer: {
      style: 'light',
      logo: {
        alt: 'OpenWoo logo',
        src: 'img/openwoo-logo.svg',
      },
      links: [
        {
          title: 'Links',
          items: [
            {label: 'Home',            to: '/'},
            {label: 'Slack',           href: 'https://samenorganiseren.slack.com/archives/C067Q3UE9F0'},
            {label: 'GitHub',          href: 'https://github.com/ConductionNL/openwoo-app-website'},
            {label: 'Open Webconcept', href: 'https://openwebconcept.nl/'},
          ],
        },
        {
          title: 'Product',
          items: [
            {label: 'Kosten',               to: '/docs/reference/pricing'},
            {label: 'Privacy',              to: '/docs/reference/privacy'},
            {label: 'Beveiliging',          to: '/docs/reference/security'},
            {label: 'Toegankelijkheid',     to: '/docs/reference/accessibility'},
            {label: 'Roadmap',              to: '/docs/reference/roadmap'},
            {label: 'Veelgestelde vragen',  to: '/docs/reference/faq'},
          ],
        },
        {
          title: 'Techniek',
          items: [
            {label: 'Architectuur',   to: '/docs/category/architectuur/'},
            {label: 'Installatie',    to: '/docs/Technical/installation'},
            {label: 'Configuratie',   to: '/docs/Technical/configuration'},
            {label: 'Naar productie', to: '/docs/Technical/production'},
            {label: 'API',            to: '/docs/api-overview'},
          ],
        },
        {
          title: 'Conduction',
          items: [
            {label: 'Website',  href: 'https://www.conduction.nl/'},
            {label: 'Solution', href: 'https://www.conduction.nl/solutions/openwoo'},
            {label: 'Academy',  href: 'https://www.conduction.nl/academy/?app=openwoo'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} OpenWoo — een open source-publicatieplatform uit de Conduction-familie. EUPL-1.2.`,
    },
  },
};

module.exports = config;
