// @ts-check

/**
 * Sidebar for openwoo.conduction.nl docs.
 *
 * Fleet-canonical layout (matches openregister/docs):
 *   docs/
 *     index.md              → docs landing
 *     community-meetings.md → maandelijkse community-bijeenkomsten + opnames
 *     UseCases/             → top user-facing scenarios
 *     Architecture/         → systeemarchitectuur-overzicht
 *     Integrations/         → API-koppelvlak + fulltext-search + bronnenoverzicht
 *     Technical/            → configuratie, productie, testscenarios
 *     reference/            → faq, privacy, accessibility, pricing, sla
 */
module.exports = {
  tutorialSidebar: [
    'index',
    'api',
    'community-meetings',
    {
      type: 'category',
      label: 'Use cases',
      link: {
        type: 'generated-index',
        description: 'De meest gestelde "wat wil je bereiken"-vragen waar OpenWoo een antwoord op geeft.',
      },
      items: [
        'UseCases/actieve-openbaarmaking',
        'UseCases/publicatie-vanuit-zaaksysteem',
      ],
    },
    {
      type: 'category',
      label: 'Architectuur',
      link: {
        type: 'generated-index',
        description: 'Hoe OpenWoo onder de motorkap in elkaar zit.',
      },
      items: [
        'Architecture/overview',
      ],
    },
    {
      type: 'category',
      label: 'Integraties',
      link: {
        type: 'generated-index',
        description: 'Ondersteunde bronnen, API-koppelvlak en full-text search.',
      },
      items: [
        'Integrations/ondersteunde-bronnen',
        'Integrations/api-koppelvlak',
        'Integrations/fulltext-search',
      ],
    },
    {
      type: 'category',
      label: 'Technical',
      link: {
        type: 'generated-index',
        description: 'Configuratie, productie, testscenarios.',
      },
      items: [
        'Technical/configuration',
        'Technical/production',
        'Technical/test-scenarios',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        description: 'FAQ, privacy, toegankelijkheid, kosten, SLA.',
      },
      items: [
        'reference/faq',
        'reference/privacy',
        'reference/accessibility',
        'reference/pricing',
        'reference/sla',
      ],
    },
    /* Release notes per OpenWoo-release. Statisch hand-geschreven (voor
       nu); elke release krijgt zijn eigen markdown onder docs/Releases/.
       Sidebar bouwt zich op uit het bestand-overzicht via `autogenerated`.
       Toekomst: semi-dynamisch via commit-labels of changelog-pipeline. */
    {
      type: 'category',
      label: 'Releases',
      link: {
        type: 'generated-index',
        description: 'OpenWoo release notes per versie — wijzigingen in woo-website-template-apiv2 (de runtime) plus de gebruikte component-versies. Nieuwste eerst.',
      },
      items: [{type: 'autogenerated', dirName: 'Releases'}],
    },
  ],
};
